
package com.grdf.poc.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Qc10452", targetNamespace = "http://poc.grdf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Qc10452 {


    /**
     * 
     * @param data2Literal
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "literalData", targetNamespace = "")
    @RequestWrapper(localName = "qc10452Literal", targetNamespace = "http://poc.grdf.com/", className = "com.grdf.poc.jaxws.Qc10452Literal")
    @ResponseWrapper(localName = "qc10452LiteralResponse", targetNamespace = "http://poc.grdf.com/", className = "com.grdf.poc.jaxws.Qc10452LiteralResponse")
    public String qc10452Literal(
        @WebParam(name = "data2literal", targetNamespace = "")
        String data2Literal);

    /**
     * 
     * @param data2Escape
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "escapedData", targetNamespace = "")
    @RequestWrapper(localName = "qc10452Escaped", targetNamespace = "http://poc.grdf.com/", className = "com.grdf.poc.jaxws.Qc10452Escaped")
    @ResponseWrapper(localName = "qc10452EscapedResponse", targetNamespace = "http://poc.grdf.com/", className = "com.grdf.poc.jaxws.Qc10452EscapedResponse")
    public String qc10452Escaped(
        @WebParam(name = "data2escape", targetNamespace = "")
        String data2Escape);

    /**
     * 
     * @param data2Unescape
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "unescapedData", targetNamespace = "")
    @RequestWrapper(localName = "qc10452Unescaped", targetNamespace = "http://poc.grdf.com/", className = "com.grdf.poc.jaxws.Qc10452Unescaped")
    @ResponseWrapper(localName = "qc10452UnescapedResponse", targetNamespace = "http://poc.grdf.com/", className = "com.grdf.poc.jaxws.Qc10452UnescapedResponse")
    public String qc10452Unescaped(
        @WebParam(name = "data2unescape", targetNamespace = "")
        String data2Unescape);

}
