
package com.grdf.poc.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Qc10452Service", targetNamespace = "http://www.poc.grdf.com", wsdlLocation = "http://127.0.1.1:7001/qc10452/qc10452?WSDL")
public class Qc10452Service
    extends Service
{

    private final static URL QC10452SERVICE_WSDL_LOCATION;
    private final static WebServiceException QC10452SERVICE_EXCEPTION;
    private final static QName QC10452SERVICE_QNAME = new QName("http://www.poc.grdf.com", "Qc10452Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.1.1:7001/qc10452/qc10452?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QC10452SERVICE_WSDL_LOCATION = url;
        QC10452SERVICE_EXCEPTION = e;
    }

    public Qc10452Service() {
        super(__getWsdlLocation(), QC10452SERVICE_QNAME);
    }

    public Qc10452Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Qc10452Srv
     */
    @WebEndpoint(name = "Qc10452Port")
    public Qc10452Srv getQc10452Port() {
        return super.getPort(new QName("http://www.poc.grdf.com", "Qc10452Port"), Qc10452Srv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Qc10452Srv
     */
    @WebEndpoint(name = "Qc10452Port")
    public Qc10452Srv getQc10452Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.poc.grdf.com", "Qc10452Port"), Qc10452Srv.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QC10452SERVICE_EXCEPTION!= null) {
            throw QC10452SERVICE_EXCEPTION;
        }
        return QC10452SERVICE_WSDL_LOCATION;
    }

}
